-- ╔══════════════════════════════════════════════════════════════════╗
-- ║                    HYPRLOCK LUA CONFIGURATION                    ║
-- ╚══════════════════════════════════════════════════════════════════╝
-- Custom screen lock configuration for hyprlock written in Lua.
-- Reference: https://wiki.hypr.land/Hypr-Ecosystem/hyprlock/

local noctalia = require("noctalia")
local colors = noctalia.colors or {
    primary   = "rgb(58a6ff)",
    surface   = "rgb(010409)",
    secondary = "rgb(bc8cff)",
    error     = "rgb(f85149)",
}

-- Hyprland-side session lock configuration
hl.config({
    misc = {
        allow_session_lock_restore = true,
    },
})

local hyprlock = {}

-- Hyprlock Widget & Styling Options
hyprlock.options = {
    general = {
        disable_loading_bar = true,
        hide_cursor         = true,
        grace               = 0,
        no_fade_in          = false,
        immediate_render    = true,
        ignore_empty_input  = true,
        text_trim           = true,
    },
    background = {
        path              = "screenshot",
        color             = "rgba(1, 4, 9, 0.9)",
        blur_passes       = 4,
        blur_size         = 6,
        noise             = 0.0117,
        contrast          = 0.9,
        brightness        = 0.8,
        vibrancy          = 0.2,
        vibrancy_darkness = 0.2,
    },
    image = {
        path          = os.getenv("HOME") .. "/.face.icon",
        size          = 120,
        rounding      = -1,
        border_size   = 3,
        border_color  = "rgba(188, 140, 255, 0.9)",
        position      = "0, 0",
        halign        = "center",
        valign        = "center",
        shadow_passes = 2,
        shadow_size   = 4,
        shadow_color  = "rgba(0, 0, 0, 0.5)",
    },
    input_field = {
        size              = "320, 56",
        outline_thickness = 0,
        dots_size         = 0.25,
        dots_spacing      = 0.2,
        dots_center       = true,
        dots_rounding     = -1,
        outer_color       = "rgba(0, 0, 0, 0)",
        inner_color       = "rgba(0, 0, 0, 0)",
        font_color        = "rgb(240, 246, 252)",
        font_family       = "Inter, Sans-Serif",
        fade_on_empty     = true,
        placeholder_text  = '""',
        rounding          = 18,
        check_color       = "rgba(0, 0, 0, 0)",
        fail_color        = "rgba(0, 0, 0, 0)",
        fail_text         = '<i>$FAIL <b>($ATTEMPTS)</b></i>',
        position          = "0, -150",
        halign            = "center",
        valign            = "center",
    },
    clock = {
        text          = "$TIME",
        color         = "rgba(240, 246, 252, 1.0)",
        font_size     = 105,
        font_family   = "Inter Bold, Sans-Serif",
        position      = "0, 240",
        shadow_passes = 2,
        shadow_size   = 5,
    },
    date = {
        text        = 'cmd[update:1000] echo "$(date +\'%A, %B %d\')"',
        color       = "rgba(188, 140, 255, 0.95)",
        font_size   = 22,
        font_family = "Inter Medium, Sans-Serif",
        position    = "0, 130",
        shadow_passes = 1,
        shadow_size = 2,
    },
    user = {
        text        = "󰀉  $USER",
        color       = "rgba(58, 166, 255, 0.95)",
        font_size   = 16,
        font_family = "Inter SemiBold, Sans-Serif",
        position    = "0, -85",
        shadow_passes = 1,
        shadow_size = 2,
    },
    layout = {
        text        = "󰌌  $LAYOUT",
        color       = "rgba(139, 148, 158, 0.75)",
        font_size   = 12,
        font_family = "Inter, Sans-Serif",
        position    = "0, -220",
    },
}

-- Generate configuration for hyprlock binary
function hyprlock.generate_config()
    local conf_path = os.getenv("HOME") .. "/.config/hypr/hyprlock.conf"
    local f = io.open(conf_path, "w")
    if not f then return end

    local content = [[
# Auto-generated by lua/hyprlock.lua (Hyprland Lua System)
# Documentation: https://wiki.hypr.land/Hypr-Ecosystem/hyprlock/

general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
    no_fade_in = false
    immediate_render = true
    ignore_empty_input = true
    text_trim = true
}

background {
    monitor =
    path = ]] .. hyprlock.options.background.path .. [[

    color = ]] .. hyprlock.options.background.color .. [[

    blur_passes = ]] .. hyprlock.options.background.blur_passes .. [[

    blur_size = ]] .. hyprlock.options.background.blur_size .. [[

    noise = ]] .. hyprlock.options.background.noise .. [[

    contrast = ]] .. hyprlock.options.background.contrast .. [[

    brightness = ]] .. hyprlock.options.background.brightness .. [[

    vibrancy = ]] .. hyprlock.options.background.vibrancy .. [[

    vibrancy_darkness = ]] .. hyprlock.options.background.vibrancy_darkness .. [[

}

animations {
    enabled = true
    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    animation = fadeIn, 1, 3.5, easeOutQuint
    animation = fadeOut, 1, 3.5, easeOutQuint
    animation = inputFieldColors, 1, 2, easeOutQuint
}

label {
    monitor =
    text = ]] .. hyprlock.options.clock.text .. [[

    color = ]] .. hyprlock.options.clock.color .. [[

    font_size = ]] .. hyprlock.options.clock.font_size .. [[

    font_family = ]] .. hyprlock.options.clock.font_family .. [[

    position = ]] .. hyprlock.options.clock.position .. [[

    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 5
    shadow_color = rgba(0, 0, 0, 0.5)
}

label {
    monitor =
    text = ]] .. hyprlock.options.date.text .. [[

    color = ]] .. hyprlock.options.date.color .. [[

    font_size = ]] .. hyprlock.options.date.font_size .. [[

    font_family = ]] .. hyprlock.options.date.font_family .. [[

    position = ]] .. hyprlock.options.date.position .. [[

    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 2
    shadow_color = rgba(0, 0, 0, 0.4)
}

image {
    monitor =
    path = ]] .. hyprlock.options.image.path .. [[

    size = ]] .. hyprlock.options.image.size .. [[

    rounding = ]] .. hyprlock.options.image.rounding .. [[

    border_size = ]] .. hyprlock.options.image.border_size .. [[

    border_color = ]] .. hyprlock.options.image.border_color .. [[

    position = ]] .. hyprlock.options.image.position .. [[

    halign = ]] .. hyprlock.options.image.halign .. [[

    valign = ]] .. hyprlock.options.image.valign .. [[

    shadow_passes = ]] .. hyprlock.options.image.shadow_passes .. [[

    shadow_size = ]] .. hyprlock.options.image.shadow_size .. [[

    shadow_color = ]] .. hyprlock.options.image.shadow_color .. [[

}

label {
    monitor =
    text = ]] .. hyprlock.options.user.text .. [[

    color = ]] .. hyprlock.options.user.color .. [[

    font_size = ]] .. hyprlock.options.user.font_size .. [[

    font_family = ]] .. hyprlock.options.user.font_family .. [[

    position = ]] .. hyprlock.options.user.position .. [[

    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 2
    shadow_color = rgba(0, 0, 0, 0.3)
}

input-field {
    monitor =
    size = ]] .. hyprlock.options.input_field.size .. [[

    outline_thickness = ]] .. hyprlock.options.input_field.outline_thickness .. [[

    dots_size = ]] .. hyprlock.options.input_field.dots_size .. [[

    dots_spacing = ]] .. hyprlock.options.input_field.dots_spacing .. [[

    dots_center = true
    dots_rounding = -1
    outer_color = ]] .. hyprlock.options.input_field.outer_color .. [[

    inner_color = ]] .. hyprlock.options.input_field.inner_color .. [[

    font_color = ]] .. hyprlock.options.input_field.font_color .. [[

    font_family = ]] .. hyprlock.options.input_field.font_family .. [[

    fade_on_empty = ]] .. tostring(hyprlock.options.input_field.fade_on_empty) .. [[

    placeholder_text = ]] .. hyprlock.options.input_field.placeholder_text .. [[

    hide_input = false
    rounding = ]] .. hyprlock.options.input_field.rounding .. [[

    check_color = ]] .. hyprlock.options.input_field.check_color .. [[

    fail_color = ]] .. hyprlock.options.input_field.fail_color .. [[

    fail_text = ]] .. hyprlock.options.input_field.fail_text .. [[

    position = ]] .. hyprlock.options.input_field.position .. [[

    halign = center
    valign = center
    zindex = 0
}

label {
    monitor =
    text = ]] .. hyprlock.options.layout.text .. [[

    color = ]] .. hyprlock.options.layout.color .. [[

    font_size = ]] .. hyprlock.options.layout.font_size .. [[

    font_family = ]] .. hyprlock.options.layout.font_family .. [[

    position = ]] .. hyprlock.options.layout.position .. [[

    halign = center
    valign = center
}
]]
    f:write(content)
    f:close()
end

-- Generate hyprlock configuration automatically
hyprlock.generate_config()

return hyprlock
